version: "3"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
      - NODE_ENV=development
    command: npm run dev
    mem_limit: 512m
    cpus: 0.5